### ISSUE TITLE
surftrace 执行 -S 命令报错

### ISSUE THREAD

**Issue by zhongwuq** [aliyun/surftrace#1]
![image](https://user-images.githubusercontent.com/9779141/148480910-0277be84-18e2-42d9-8782-eab75cebc7e7.png)
首次运行不会报错，第二次运行的时候会报错。

另外用不带-S参数直接跑，Ctrl-C之后，再重新执行 -S 命令，首次不会有问题，第二次运行会报错，怀疑是首次执行之后有资源残留？
./surftrace.py 'p get_files_struct comm=%0->comm uesrs=X%0->mm->mm_users'
./surftrace.py 'p get_files_struct comm=%0->comm uesrs=X%0->mm->mm_users' -S

**Comment by liaozhaoyan** [comment]
更新版本已经解决
